version : '3'

services:
  server:
    build: .
    container_name: Text-To-Speech
    stdin_open: true
    tty: true
    network_mode: host
    #ports:
    #- 8000:8000
    devices: 
    - /dev/snd:/dev/snd # ubuntu