version : '3.8'

#
# docker-compose up -d
#

services:
  tts-api-server:
    build: .
    container_name: tts-api-server
    stdin_open: true
    tty: true
    ports:
    - 8000:8000
    #devices: 
    #- /dev/snd:/dev/snd # ubuntu/wsl